
# 此文件是 kh-plugin 的默认配置模板，会随插件版本更新。
# 如需自定义，请在同目录 config.yaml 中仅填写需要覆盖的字段。
# config.yaml 未定义的字段将自动使用本文件中的默认值。
# 不要将个人配置直接写在本文件中，否则插件更新时可能被覆盖。



# 【互通组配置】
# 什么时候需要配置互通组：对于同一组织体系下的多个群，其群员会有一定重复。即当“我们”都重复加了某组织的1群和2群，“你”在这两个群的身份都对“我”可见，那么在查询“你”的身份时，Bot同时提供“你”在另一个群的身份则有助于“我”了解“你”是谁。
# 在下方使用群号配置互通组，各组可独立，可交叉。
# 如不需要此功能可以留空。
# 示例格式：
# linkedGroups:
# 示例互通组1：云崽体系下的多个群聊(bushi)
#    - [
#        114514,  //napcat官方1群
#        1919810, //云崽官方1群
#        91919191 //云崽官方2群
#    ]
# 示例互通组2：喵喵官方交流群123（bushi）
#    - [
#        114514,  //napcat云崽官方1群
#        666666,  //喵喵官方1群
#        88888888 //喵喵官方2群
#    ]

linkedGroups:
    - [
       
    ]
    - [

    ]



# 【记录条数限制】
#  每个用户在单个群内最多保存的记录条数，超过这个值的最早记录将被丢弃。
maxSaveLength: 100
# 开合时图中最多展示的记录数，超过这个值的更早记录将不被显示。减小这个值以缩小图片大小，提高响应速度。  使用大写KH可绕过此限制从而渲染完整的全部记录。
maxRenderLength: 10
# KH 卡片自适应倒序阈值。
# 要渲染的记录数超过此值时，历史身份卡片按倒序显示，最新记录在前，方便查看。
# 0 表示始终倒序；999 可视为始终正序。
reverseHistoryThreshold: 999


# 【自动更新与定时任务】
# 要定时自动更新全体成员信息的群列表
# 插件会在指定的时间，自动更新这些群的全部群员的信息。
autoUpdateGroups: [
#    114514,   
#    1919810,
]

# 定时更新 Cron 表达式（默认每天凌晨 03:30执行一次）
updateSchedule: '0 30 3 * * *'  #每天凌晨3:30
#updateSchedule: '0 */10 * * * *'  #每10分钟
#updateSchedule: '0 0 */12 * * *'  #每12小时




# 【实时推送配置】
# 这些群里有人改名换头像后发言，机器人会捕获更新、并在群里推送历史身份卡片。
# 此配置只是用于控制是否进行推送，即便不配置，bot依然会以默认10分钟的cd来判断在任何群发言了的任何群员的身份信息是否发生更新、并静默保存新身份资料。如不需要更新请配置黑白名单。
# 对每个人的检测默认有10分钟间隔所以会有变更信息后并不立刻推送的可能。
# 如果对该群配置了定时自动更新全员信息，那么如果该用户改名换头像后保持静默直到bot自动更新了其新身份后才发言，自然也不会触发推送。
notifyGroups: [
#    114514,   
#    1919810,
]
# 实时推送图片中包含的历史条数
maxNotifyRenderLength: 2
# 群员发言触发检测的冷却时间（秒）
monitorCD: 600    # 默认10分钟




# 【排行榜配置】
# 换头大王/马甲大王排行榜显示的最多人数
rankLimit: 50




# 【黑白名单配置】
# 如无特殊需要，可不编辑下方三个名单。插件将默认对全部群生效。
# 群白名单：配置后，全部的定时更新和群员发言实时检测将只在这些群生效。配置此项将导致群黑名单不再生效。
groupWhitelist: [
#    114514,   
#    1919810,
]
# 群黑名单：黑名单中的群，插件始终不更新其任何群员的信息。仅在群白名单为空时，群黑名单才生效。
# 注意：主人依旧可以使用 更新群员信息 或 静默更新信息 来手动更新群员（黑名单用户除外）的信息。
groupBlacklist: [
#    114514,   
#    1919810,
]
# 用户黑名单：黑名单中的用户，插件将始终不更新其在任何群中的信息。
userBlacklist: [
#    114514,   
#    1919810,
]




# 【潜水群配置】
# 潜水群列表：在这些群中，依然会正常记录群员的信息，但无法触发本插件的任何文本或图片响应，以此避免暴露Bot身份。
# 主人在潜水群发送“更新群员信息”会转为执行“静默更新信息”。
divingGroups: [
#    114514,   
]
